import { Brand } from '@/types'

// spreadsheetId       = Meta Ads sheet ID
// shopifySpreadsheetId = Shopify sheet ID (ecommerce only, shown by default)
//
// Shopify sheet expected columns (row 1 headers):
//   Date | Sessions | Orders | Revenue | AOV | Conversion Rate | New Customers | Returning Customers
//
// Meta Ads sheet expected columns (row 1 headers):
//   Date | Ad Spend | Revenue | Impressions | Clicks | ATC | Purchases | ROAS | CPA | CR | CTR | AOV

export const BRANDS: Brand[] = [
  {
    id: 'ecom-SCHICK-A-WALK',
    name: 'SCHICK-A-WALK',
    vertical: 'ecommerce',
    spreadsheetId: '1qBBKQJS4x2cjZtMttNwq-R6x7JzfsdmVBkpc4fALkew',
    sheetName: 'Daily Tracker (Meta Ads)',
    shopifyAnalyticsSpreadsheetId: '1F1Is_owORKrTbU5ERqmgDIrQsfpv4kM4_um30-Eiohg',
    shopifyOverviewSheet:     'Overview',
    shopifyProductSheet:      'Product Performance',
    shopifyLocationSheet:     'Sessions by Location',
    shopifyReferrerSheet:     'Sessions by Referrer',
    shopifyLandingPageSheet:  'Sessions by Landing Page',
  },
  {
    id: 'ecom-osn',
    name: 'OSN',
    vertical: 'ecommerce',
    spreadsheetId: '1LhmdUEZrk5xGp6dfnpDdHu4rk6ZhReisxBNV2GP5lXI',
    sheetName: 'Daily Tracker (Meta Ads)',
    shopifyAnalyticsSpreadsheetId: '1Vnfxf4c_jOamwTQp14RNuylIOnYxI_Zedi6JK-gTcdg',
    shopifyOverviewSheet:     'Overview',
    shopifyProductSheet:      'Product Performance',
    shopifyLocationSheet:     'Sessions by Location',
    shopifyReferrerSheet:     'Sessions by Referrer',
    shopifyLandingPageSheet:  'Sessions by Landing Page',
  },
  {
    id: 'ecom-Saalvi',
    name: 'Saalvi',
    vertical: 'ecommerce',
    spreadsheetId: '1ucH0BZxVcyfnwCPjXliv3qapCz5ic0t2qbFNg05oCTg',
    sheetName: 'Daily Tracker (Meta Ads)',
    shopifyAnalyticsSpreadsheetId: '1fzmvBTJFAttexANt9oVJKilsZ_jAwA-94pT2Spw9xds',
    shopifyOverviewSheet:     'Overview',
    shopifyProductSheet:      'Product Performance',
    shopifyLocationSheet:     'Sessions by Location',
    shopifyReferrerSheet:     'Sessions by Referrer',
    shopifyLandingPageSheet:  'Sessions by Landing Page',
  },
  {
    id: 'ecom-Maniyar Marketing',
    name: 'Maniyar',
    vertical: 'ecommerce',
    spreadsheetId: '1_S5Y626nXq1-gTb1BEnscvIwmYk2wNVzFWmqc-Kjhxc',
    sheetName: 'Daily Tracker (Meta Ads)',
    // Multi-sheet Shopify Analytics (spreadsheet: 1IbMvSsT8AR8SxiO83uzL34UOEUs-ZCO75EV3RbfpX4I)
    shopifyAnalyticsSpreadsheetId: '1IbMvSsT8AR8SxiO83uzL34UOEUs-ZCO75EV3RbfpX4I',
    shopifyOverviewSheet:     'Overview',
    shopifyProductSheet:      'Product Performance',
    shopifyLocationSheet:     'Sessions by Location',
    shopifyReferrerSheet:     'Sessions by Referrer',
    shopifyLandingPageSheet:  'Sessions by Landing Page',
  },
  {
    id: 'ecom-Evday_Marketing_Metrics_Tracker',
    name: 'Evday',
    vertical: 'ecommerce',
    spreadsheetId: '16gb3FXSF3cIG6C5waVXfqWANQQrUY0URDpJKtxUOjFM',
    sheetName: 'Daily Tracker (Meta Ads)',
    shopifyAnalyticsSpreadsheetId: '1V4L37EOVV7P5JiD-DhafBcwAJiZA3aCSsNiuFyrKBeU',
    shopifyOverviewSheet:     'Overview',
    shopifyProductSheet:      'Product Performance',
    shopifyLocationSheet:     'Sessions by Location',
    shopifyReferrerSheet:     'Sessions by Referrer',
    shopifyLandingPageSheet:  'Sessions by Landing Page',
  },
  {
    id: 'ecom-Skinloom_Marketing_Metrics_Tracker',
    name: 'Skinloom',
    vertical: 'ecommerce',
    spreadsheetId: '1AqsUH_d7aesZRCUNspkPBbUKz8Hmlj7LG3s2gHrJ8IE',
    sheetName: 'Daily Tracker (Meta Ads)',
    shopifyAnalyticsSpreadsheetId: '1PiCE1hIh_oNsREJ90UyASA0IMZFTVjcTsDMsKi4dLRk',
    shopifyOverviewSheet:     'Overview',
    shopifyProductSheet:      'Product Performance',
    shopifyLocationSheet:     'Sessions by Location',
    shopifyReferrerSheet:     'Sessions by Referrer',
    shopifyLandingPageSheet:  'Sessions by Landing Page',
  },
  {
    id: 'ecom-milkvilla',
    name: 'Milkvilla',
    vertical: 'ecommerce',
    spreadsheetId: '1SZO-oo_yFXNFUEsPikvLVzJZcHl-vWaiE5U4YcLPzAY',
    sheetName: 'Daily Tracker (Meta Ads)',
    shopifySpreadsheetId: '1SZO-oo_yFXNFUEsPikvLVzJZcHl-vWaiE5U4YcLPzAY',
    shopifySheetName: 'Shopify',
    shopifyAnalyticsSheetName: 'Shopify Analytics',
  },
  {
    id: 'hospital-Palve labs',
    name: 'Palve Labs',
    vertical: 'hospital',
    spreadsheetId: '1fGCGHQyQo6rv8v6GszzhwDuoTeYXEQ29FQxEPTxaDFQ',
    sheetName: 'Meta Ads - Daily',
  },
  {
    id: 'hospital-Rysewell hospital',
    name: 'Rysewell Hospital',
    vertical: 'hospital',
    spreadsheetId: '1anoClVpcFcRhyZA1tfUvB8POrg1AHKkKnoCdEs15mW8',
    sheetName: 'Meta Ads - Daily',
  },
  {
    id: 'hospital-clinic2000',
    name: 'Clinic 2000',
    vertical: 'hospital',
    spreadsheetId: '1FCwkBs5RIp172eW847StmE-WStchD4mM9A533VOjvPQ',
    sheetName: 'Meta Ads - Daily',
  },
  {
    id: 'hospital-SUNRISE-shamshabad',
    name: 'Sunrise Shamshabad',
    vertical: 'hospital',
    spreadsheetId: '1vr0UmDImaXAB_CLa3Mwa95DyNAHbyEJ2ssSUISOxQJc',
    sheetName: 'Meta Ads - Daily',
  },
  {
    id: 'hospital-SUNRISE-himayat',
    name: 'Sunrise Himayat Nagar',
    vertical: 'hospital',
    spreadsheetId: '1c9AyEkUF7DVWxGByXTWrIGmSnTrnfKsfYIikMZrsJHY',
    sheetName: 'Meta Ads - Daily',
  },
  {
    id: 'other-brand-1',
    name: 'Other Brand 1',
    vertical: 'other',
    spreadsheetId: '',
  },
]
